### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by petealbertson** [HelpfulHuman/Helpful-CLI#4]
React/Redux/serverless app has occasional issues with infinite page refresh loops after code updates.

**Comment by NickGlenn** [comment]
Investigating this, Rollup team is aware: https://github.com/rollup/rollup/issues/883

**Comment by dabellator** [comment]
only happens at random.  @petealbertson if you have a way of recreating the issue, I'd love to take a look

**Comment by petealbertson** [comment]
@dabellator I can successfully reproduce the error through the following steps:
1. Write bad React code.
2. Receive error in browser console.
3. Fix error in code.
4. Browser refreshes ad infinitum.

**Comment by petealbertson** [comment]
@NickGlenn @dabellator Bump. This is a pretty consistent issue that's become more than just a nuisance. It happens roughly every 3rd or 4th save in a React project.

**Comment by NickGlenn** [comment]
@petealbertson Still investigating... I'm going to try and isolate rollup-watch this weekend to see if it's just the rollup-watch build process on its own or some kind of side effect caused by piping multiple tasks together in NPM scripts.

**Comment by NickGlenn** [comment]
This issue is now a non issue.
