### ISSUE TITLE
Console error: ReferenceError: validateProperty is not defined

### ISSUE THREAD

**Issue by petealbertson** [HelpfulHuman/Helpful-CLI#5]
![image](https://cloud.githubusercontent.com/assets/5597250/19665235/e374e326-99f8-11e6-84bf-1fad0664df9c.png)

All the time. Won't go away.

**Comment by NickGlenn** [comment]
@dabellator Has the fix for this.  I believe we need to add `rollup-plugin-replace` to handle `process.env.NODE_ENV` in order for tree shaking to not tear out React development helpers.

**Comment by dabellator** [comment]
I'll make a PR to the CLI with the fix, but as Nick mentioned, this is an annoyance and not a blocker
